### PR TITLE
#3 Issue Solved

### PR DESCRIPTION
**Pull request by Rishi22-Coding**
Signed-off-by: Saptarshi Patra <saptarshi.patra.22@gmail.com>

### CODE REVIEW

**Comment by Rishi22-Coding** [comment]
@AaquibAli How is it??

**Comment by AaquibAli** [comment]
@Rishi22-Coding  can you deployed this so i can see the changes live

**Comment by Rishi22-Coding** [comment]
Should i deploy in github pages?

**Comment by AaquibAli** [comment]
@Rishi22-Coding  your branch has conflict please resolve it

**Comment by AaquibAli** [comment]
i solve the conflict you just have to make it look better  on hover the buttons.

**Comment by Rishi22-Coding** [comment]
Okay let me do it..!!

**Comment by Rishi22-Coding** [comment]
@AaquibAli I think now it looks great.. What do you think??

**Comment by AaquibAli** [comment]
please send the deployment link? @Rishi22-Coding

**Comment by Rishi22-Coding** [comment]
okay wait

**Comment by Rishi22-Coding** [comment]
@AaquibAli check here - https://rishi22-coding.github.io/Aaquib-Ali-Portfolio/

**Pull request merged**
